import { ScheduleDataItem } from "./ScheduleDataItem";

export const SuccursalData = [
    { Text: "Vilray", Id: 1, OwnerColor: "#ffaa00" },
    { Text: "Plateau", Id: 2, OwnerColor: "#f8a398" },
];

export const ComiteData = [
    { Text: "Comité Bois", Id: 1, OwnerColor: "#f8a398", SuccursalId: 1 },
    { Text: "Comité Outil", Id: 2, OwnerColor: "#7499e1", SuccursalId: 1 },
    { Text: "Comité Vélo", Id: 3, OwnerColor: "#4caf50", SuccursalId: 2 },
    { Text: "Comité Outil", Id: 4, OwnerColor: "#ff9800", SuccursalId: 2 },
];
export const PosteData = [
    { Text: "Accueil", Id: 1 },
    { Text: "Decouverte", Id: 2 },
];

export const BenevoleData = [
    { Name: "Francis", Id: 1, ComiteId: 1 },
    { Name: "Benois", Id: 2, ComiteId: 1 },
    { Name: "Jean", Id: 3, ComiteId: 2 },
    { Name: "Marie", Id: 4, ComiteId: 2 },
    { Name: "Lucie", Id: 5, ComiteId: 3 },
    { Name: "Paul", Id: 6, ComiteId: 3 },
    { Name: "Pierre", Id: 7, ComiteId: 4 },
    { Name: "Sophie", Id: 8, ComiteId: 4 },
    { Name: "Alice", Id: 9, ComiteId: 1 },
    { Name: "Bob", Id: 10, ComiteId: 2 },
    { Name: "Charlie", Id: 11, ComiteId: 3 },
    { Name: "David", Id: 12, ComiteId: 4 },
];
export const AffectationData = [
    {
        Id: 1,
        Date: new Date(2018, 5, 1, 10, 0),
        PosteID: 1,
        BenevoleID: 1,
        ScheduleDataItemID: 1,
    },
    {
        Id: 2,
        Date: new Date(2018, 5, 1, 10, 0),
        PosteID: 2,
        BenevoleID: null,
        ScheduleDataItemID: 1,
    },
    {
        Id: 3,
        Date: new Date(2018, 5, 2, 10, 30),
        PosteID: 1,
        BenevoleID: null,
        ScheduleDataItemID: 2,
    },
    {
        Id: 4,
        Date: new Date(2018, 5, 2, 11, 0),
        PosteID: 2,
        BenevoleID: null,
        ScheduleDataItemID: 2,
    },
];
export const EventsData: ScheduleDataItem[] = [
    {
        Id: 1,
        Subject: "Developers Meeting",
        StartTime: new Date(2018, 5, 1, 10, 0),
        EndTime: new Date(2018, 5, 1, 11, 0),
        RecurrenceRule: "FREQ=WEEKLY;INTERVAL=1;BYDAY=MO,TU,WE,TH,FR",
        SuccursalID: 1,
        ComiteID: 1,
        PosteIDs: [1, 2],
    },
    /* {
        Id: 2,
        Subject: "Test report Validation",
        StartTime: new Date(2018, 5, 2, 10, 30),
        EndTime: new Date(2018, 5, 2, 13, 0),
        RecurrenceRule: "FREQ=WEEKLY;INTERVAL=1;BYDAY=MO,WE,FR",
        SuccursalID: 1,
        ComiteID: 2,
    },
    {
        Id: 3,
        Subject: "Requirement planning",
        StartTime: new Date(2018, 5, 4, 9, 30),
        EndTime: new Date(2018, 5, 4, 10, 45),
        SuccursalID: 2,
        ComiteID: 1,
    },
    {
        Id: 4,
        Subject: "Bug Automation",
        StartTime: new Date(2018, 5, 2, 11, 0),
        EndTime: new Date(2018, 5, 2, 13, 0),
        RecurrenceRule: "FREQ=WEEKLY;INTERVAL=1;BYDAY=MO,WE,FR",
        SuccursalID: 2,
        ComiteID: 2,
    },
    {
        Id: 5,
        Subject: "Timeline estimation",
        StartTime: new Date(2018, 5, 3, 10, 0),
        EndTime: new Date(2018, 5, 3, 12, 0),
        SuccursalID: 1,
        ComiteID: 1,
    },
    {
        Id: 6,
        Subject: "Timeline estimation",
        StartTime: new Date(2018, 5, 3, 13, 0),
        EndTime: new Date(2018, 5, 3, 15, 0),
        SuccursalID: 2,
        ComiteID: 1,
    },
    {
        Id: 7,
        Subject: "Functionality testing",
        StartTime: new Date(2018, 5, 4, 14, 0),
        EndTime: new Date(2018, 5, 4, 15, 30),
        SuccursalID: 1,
        ComiteID: 2,
    },
    {
        Id: 8,
        Subject: "Functionality testing",
        StartTime: new Date(2018, 5, 4, 19, 0),
        EndTime: new Date(2018, 5, 4, 21, 0),
        SuccursalID: 2,
        ComiteID: 2,
    },
    {
        Id: 9,
        Subject: "Workflow Analysis",
        StartTime: new Date(2018, 5, 5, 14, 0),
        EndTime: new Date(2018, 5, 5, 15, 30),
        SuccursalID: 1,
        ComiteID: 1,
    },
    {
        Id: 10,
        Subject: "Quality Analysis",
        StartTime: new Date(2018, 5, 5, 13, 0),
        EndTime: new Date(2018, 5, 5, 16, 0),
        SuccursalID: 2,
        ComiteID: 1,
    },
    {
        Id: 11,
        Subject: "Cross-browser testing",
        StartTime: new Date(2018, 5, 5, 14, 45),
        EndTime: new Date(2018, 5, 5, 16, 15),
        SuccursalID: 1,
        ComiteID: 2,
    },
    {
        Id: 12,
        Subject: "Resolution-based testing",
        StartTime: new Date(2018, 5, 5, 15, 0),
        EndTime: new Date(2018, 5, 5, 17, 30),
        SuccursalID: 2,
        ComiteID: 2,
    },
    {
        Id: 13,
        Subject: "Project Preview",
        StartTime: new Date(2018, 5, 8, 16, 0),
        EndTime: new Date(2018, 5, 8, 18, 0),
        SuccursalID: 1,
        ComiteID: 1,
    },
    {
        Id: 14,
        Subject: "Project Preview",
        StartTime: new Date(2018, 5, 8, 15, 0),
        EndTime: new Date(2018, 5, 8, 17, 30),
        SuccursalID: 2,
        ComiteID: 1,
    },
    {
        Id: 15,
        Subject: "Test report Validation",
        StartTime: new Date(2018, 5, 8, 15, 30),
        EndTime: new Date(2018, 5, 8, 17, 45),
        SuccursalID: 1,
        ComiteID: 2,
    },
    {
        Id: 16,
        Subject: "Test report Validation",
        StartTime: new Date(2018, 5, 8, 15, 0),
        EndTime: new Date(2018, 5, 8, 17, 0),
        SuccursalID: 2,
        ComiteID: 2,
    },
    {
        Id: 17,
        Subject: "Resource planning",
        StartTime: new Date(2018, 5, 6, 15, 0),
        EndTime: new Date(2018, 5, 6, 18, 0),
        SuccursalID: 1,
        ComiteID: 1,
    },
    {
        Id: 18,
        Subject: "Resource planning",
        StartTime: new Date(2018, 5, 7, 16, 0),
        EndTime: new Date(2018, 5, 7, 17, 0),
        SuccursalID: 2,
        ComiteID: 1,
    },
    {
        Id: 19,
        Subject: "Run test cases",
        StartTime: new Date(2018, 5, 7, 14, 0),
        EndTime: new Date(2018, 5, 7, 18, 0),
        SuccursalID: 1,
        ComiteID: 2,
    },
    {
        Id: 20,
        Subject: "Run test cases",
        StartTime: new Date(2018, 5, 6, 14, 0),
        EndTime: new Date(2018, 5, 6, 17, 30),
        SuccursalID: 2,
        ComiteID: 2,
    },
    {
        Id: 21,
        Subject: "Resource planning",
        StartTime: new Date(2018, 5, 7, 9, 30),
        EndTime: new Date(2018, 5, 7, 11, 30),
        SuccursalID: 2,
        ComiteID: 1,
    },
    {
        Id: 22,
        Subject: "Developers Meeting",
        StartTime: new Date(2018, 5, 1, 12, 0),
        EndTime: new Date(2018, 5, 1, 13, 0),
        RecurrenceRule: "FREQ=WEEKLY;INTERVAL=1;BYDAY=MO,TU,WE,TH,FR",
        SuccursalID: 2,
        ComiteID: 1,
    },*/
];
